create table District(
DistrictId int,
DistrictName varchar(255)
);
create table DistrictPolicestation(
PolicestationId int,
PolicestationName varchar(100),
DistrictId int;
);
create table FIRDetalis(
    actId varchar(100),
    actName varchar(100),
    complainantFirstName varchar(100),
    complainantLastName varchar(100),
    complainantMiddleName varchar(100),
    complainantName varchar(100),
    districtCd int,
    districtId int,
    districtName varchar(100),
    firBrief long(5000),
    firDate varchar(100),
    firFromDate varchar(100),
    firNumDisplay varchar(100),
    firRegDate varchar(100),
    firRegNum varchar(100),
    firStatus varchar(100),
    firToDate varchar(100),
    firToDateStr varchar(100),
    firYear varchar(100),
    isFirstSyncDone varchar(100),
    langCd int,
    linkedFirAction varchar(100),
    linkingFir varchar(100),
    linkingReason varchar(255),
    misc1 varchar(100),
    misc2 varchar(100),
    nameType varchar(100),
    orginalRecord int,
    originalRecord int,
    pageCacheRows int,
    pageStartNo int,
    pageTotalCount int,
    policeStationId int,
    policeStationName varchar(100),
    psRecordSyncOn varchar(100),
    queryKey varchar(100),
    recordCreatedBy varchar(100),
    recordCreatedOn varchar (100),
    recordStatus varchar(100),
    recordSyncFrom varchar(100),
    recordSyncOn varchar(100),
    recordSyncTo varchar(100),
    recordUpStringdBy varchar(100),
    recordUpStringdFrom varchar(100),
    recordUpStringdOn varchar(100),
    recordUpdatedFrom varchar(100),
    recordUpdatedOn varchar(100),
    recordUpdatedby varchar(100),
    regFirNo varchar(100),
    returnClassType varchar(100),
    searchCrit boolean,
    searchName varchar(100),
    sectionId varchar(100),
    sectionName varchar(100),
    stateCd int,
    stateName varchar(100),
    statusOfFir varchar(100),
    userDistrictCd int,
    userPsCd int,
    userStateCd int
);